services:
  postgres:
    image: postgres:16
    container_name: sales_db
    restart: always
    environment:
      POSTGRES_DB: sales_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge